
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NEW_LINE NUMBER program : line\n                    | line NEW_LINE programline : plus\n                | minus plus : NUMBER "+" NUMBER minus : NUMBER "-" NUMBER'
    
_lr_action_items = {'NUMBER':([0,6,7,8,],[5,5,10,11,]),'$end':([1,2,3,4,9,10,11,],[0,-1,-3,-4,-2,-5,-6,]),'NEW_LINE':([2,3,4,10,11,],[6,-3,-4,-5,-6,]),'+':([5,],[7,]),'-':([5,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,6,],[1,9,]),'line':([0,6,],[2,2,]),'plus':([0,6,],[3,3,]),'minus':([0,6,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> line','program',1,'p_program','parser_class.py',15),
  ('program -> line NEW_LINE program','program',3,'p_program','parser_class.py',16),
  ('line -> plus','line',1,'p_line','parser_class.py',18),
  ('line -> minus','line',1,'p_line','parser_class.py',19),
  ('plus -> NUMBER + NUMBER','plus',3,'p_plus','parser_class.py',23),
  ('minus -> NUMBER - NUMBER','minus',3,'p_minus','parser_class.py',28),
]
